#ifndef FRAMEWORK_H_
#define FRAMEWORK_H_


typedef enum _TestItems
{
	TESTITEMS_NONE = 0,
	TESTITEMS_FM,
	TESTITEMS_LED,
	TESTITEMS_DIGITRON,
	TESTITEMS_KEYBOARD,
	TESTITEMS_AT24C02,
	TESTITEMS_DS18B20,
	TESTITEMS_STEPMOTOR,
	TESTITEMS_JGD1602,
	TESTITEMS_WIRELESS,
	TESTITEMS_ADC,
	TESTITEMS_DAC,
	TESTITEMS_SUM,
	TESTITEMS_SN = 's',
	TESTITEMS_VER = 'v',
	TESTITEMS_HELP = 'h'
} TESTITEMS;

int PrintHeadMessage();

int ActionToRun(uchar testItems);

#endif