#ifndef KEYBOARD_H_
#define KEYBOARD_H_

typedef enum _MatrixKey
{	
	MATRIX_NONE = 0,
	MATRIX_KEY1,
	MATRIX_KEY2,
	MATRIX_KEY3,
	MATRIX_KEY4,
	MATRIX_KEY5,
	MATRIX_KEY6,
	MATRIX_KEY7,
	MATRIX_KEY8,
	MATRIX_KEY9,
	MATRIX_KEY10,
	MATRIX_KEY11,
	MATRIX_KEY12,
	MATRIX_KEY13,
	MATRIX_KEY14,
	MATRIX_KEY15,
	MATRIX_KEY16,
} MATRIX_KEY;

typedef enum _SingleKey
{
	SINGLE_NONE = 0,
	SINGLE_KEY1 = 0x10,
	SINGLE_KEY2 = 0x20,
	SINGLE_KEY3 = 0x40,
	SINGLE_KEY4 = 0x80,
} SINGLE_KEY;

int GetMatrixKey(MATRIX_KEY* matrixKey);
int GetSingleKey(SINGLE_KEY* singleKey);

#endif